### ISSUE TITLE
Seems to choke on windows

### ISSUE THREAD

**Issue by Gozala** [rvagg/polendina#10]
Produced output https://github.com/Gozala/web-encoding/runs/900213582 seems to suggest that it is confused by paths on windows:

```
> polendina --cleanup test/test-*.cjs
   Details:
    * configuration.module.rules[0].test[0]: The provided value "D:/a/web-encoding/web-encoding/test/test-lib.spec.cjs" is not an absolute path!
    * configuration.module.rules[0].test[0]: The provided value "D:/a/web-encoding/web-encoding/test/test-lib.spec.cjs" is not an absolute path!
    at webpack (D:\a\web-encoding\web-encoding\node_modules\webpack\lib\webpack.js:31:9)
    at internal/util.js:297:30
    at new Promise (<anonymous>)
    at webpack (internal/util.js:296:12)
    at Polendina.build (D:\a\web-encoding\web-encoding\node_modules\polendina\polendina.js:51:25)
    at async D:\a\web-encoding\web-encoding\node_modules\polendina\polendina-cli.js:91:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! web-encoding@1.0.0 test:browser: `polendina --cleanup test/test-*.cjs`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the web-encoding@1.0.0 test:browser script.
```

**Comment by Gozala** [comment]
Maybe related to https://github.com/webpack/webpack/issues/4530
